name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Adjust to your production branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Deploy to Production
    - name: Deploy to Server
      env:
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
      run: |
        sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no user@$SERVER_IP << 'EOF'
        cd $DEPLOY_PATH
        git pull origin main
        sudo systemctl restart nginx
        EOF
